# Instructions
# Add translated entries to the text between the "
# EX:
#     "This is text is in English": "Dieser Text ist auf Deutsch"
#       ^ original text                translated text ^
#
#  If you see {0}, {1}, keep it in the translated sentence

lang = {
    "Enable Hero Selection overlay": "",
    "Hero Selection": "",
    "Placements": "",
    "SBBTracker Ratings": "",

    "All Matches": "",
    "Latest Patch": "",
    "Previous Patch": "",
    "Today": "",
    "Yesterday": "",
    "Last 7 days": "",
    "Last 30 days": "",
    "This month": "",
    "Last month": "",

    "Captain Croc not Supported": "",
    "Simulation timed out!": "",
    "Error in simulation!": "",
    "Couldn't get player id (try reattaching)": "",
    "Waiting for match to start...": "",
    "Reattach to Storybook Brawl": "",
    "Live Graphs": "",
    "Match History": "",
    "Stats Graphs": "",
    "Join our Discord": "",
    "Report a bug": "",
    "Settings": "",
    "Export last combat": "",
    "Patch Notes": "",
    "    An update is available! Would you like to install?    ": "",
    "Yes": "",
    "Remind me later": "",
    " *DEAD*": "",
    'Open Url': "",
    'Could not open url': "",
    "Updater": "",
    "Downloading update...": "",
    "Delete all Stats": "",
    "Do you want to delete *ALL* saved stats?": "",
    "Starting Hero": "",
    "Ending Hero": "",
    "Place": "",
    "+/- MMR": "",
    "Delete": "",
    "Starting Heroes": "",
    "Ending Heroes": "",
    "Health Graph": "",
    "XP Graph": "",

    "Hero": "",
    "# Matches": "",
    "Avg Place": "",
    "Top 4": "",
    "Wins": "",
    "Net MMR": "",

    # Settings
    "General": "",
    "Data": "",
    "Overlay": "",
    "Advanced": "",
    "Streaming": "",
    "About": "",
    "Language": "",
    "Save match results": "",
    "Ignore practice and group lobbies": "",
    "Graph color palette": "",
    "Export Stats": "",
    "Delete Stats": "",
    "Last backup date": "",
    "Backup Stats": "",
    "Reimport Stats": "",
    "Reimporting is temporarily disabled": "",
    "Upload matches to sbbtracker.com": "",
    "Match uploads include your steam name, sbb id, board comps, placement, and change in mmr.": "",
    "Enable overlay": "",
    "Hide if SBB in background (restart to take effect)": "",
    "Enable 'Show Tracker' button": "",
    "Ignore windows scaling (Windows 8 compatability)": "",
    "Simulator": "",
    "Enable simulator": "",
    "Number of simulations": "",
    "Number of threads": "",
    "More threads = faster simulation but takes more computing power": "",
    "Adjust simulator transparency": "",
    "Simulator scale": "",
    "Board Comps": "",
    "Enable board comps": "",
    "Board comps scaling": "",
    "Adjust comps transparency": "",
    "Turn Display": "",
    "Enable turn display": "",
    "Turn font size (restart to resize)": "",
    "Turn transparency": "",
    "Enable export last comp button": "",
    "Hide art and show template ids": "",
    "Enable ID window": "",
    "Reset": "",
    "Show capturable score window": "",
    "Number of scores per line": "",
    "Reset scores": "",
    "Chroma-key filter #00FFFF to hide the scores background": "",
    "Show capturable overlay window": "",
    "Background color": "",
    "Enabling this will add a copy of the overlay behind your other windows.": "",
    "Wiki guide here": "",
    "Save": "",
    "Cancel": "",
    "Reimport Stats?": "",
    "Import progress": "",
    "Importer": "",
    # Overlay
    "Show Tracker": "",
    "Hide Tracker": "",
    "Turn {0} ({1})": "",
    "Scores:": "",
    # Board Comps
    "Last seen just now": "",
    "Last seen 1 turn ago": "",
    "Last seen {0} turns ago": "",
    "Not yet seen": "",
    # Graphs
    "Matches per Hero": "",
    "MMR Graph": "",
    "Cumulative MMR": "",
    "Games": "",
    "Cumulative MMR over last {0} games": "",

    # Special long messages (use 3 " to do newlines)
    """Would you like to opt into to data collection?
This enables you to upload your matches to sbbtracker.com
and contribute to the community dataset.

Things that are currently collected:
* Your steam name (this is not shared)
* Board states
* Placement
* Hero, Health, and XP
* Net MMR

This may include more game-related information as we improve 
our ability to collect it.

This info may be shared as part of the public dataset. 

For a full privacy policy, please visit sbbtracker.com/privacy.

You may change your selection at any time at Settings > Data > Upload Matches""": """""",
    #
    """
Would you like to import your old games? This is done by 
reading the record files generated by the game. This will 
import games going back to Dec 14 2021 (assuming you have not
deleted the record files).

Note that not all games are guaranteed to be imported.

If you have games already recorded from before Jan 2nd 2022
duplicated matches may appear. You may wish to backup and delete 
your current stats before doing this, or manually remove stats 
yourself.

The importer may take a long time to complete. Please be patient.



""": """"""

}
